version: '3.5'
services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    env_file: .env
  web:
    image: caddy:latest
    restart: unless-stopped
    env_file: .env
    volumes: 
       - ./caddy:/data
       - ./Caddyfile:/etc/caddy/Caddyfile
       - ./sr/web:/web
    ports:
      - 80:80
      - 443:443
  sr-admin-gui:
    image: ghcr.io/streamingriver/sr-admin-gui:latest
    restart: unless-stopped
    env_file: .env


