version: '3.5'
services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    env_file: .env
  web:
    image: caddy:latest
    restart: unless-stopped
    env_file: .env
    volumes: 
       - ./caddy:/data
       - ./Caddyfile:/etc/caddy/Caddyfile
       - ./sr/web:/web
    ports:
      - 80:80
      - 443:443
    depends_on:
      - video-gateway
  sr-admin-gui:
    image: ghcr.io/streamingriver/sr-admin-gui:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - sr-nats-proxy
  nats:
    image: nats:latest
    restart: unless-stopped
  sr-nats-proxy:
    image: ghcr.io/streamingriver/go-http-nats-proxy:main
    restart: unless-stopped
    depends_on:
      - nats
  video-transcoding:
    image: ghcr.io/streamingriver/video-transcoding:main
    restart: unless-stopped
    depends_on:
      - nats
      - video-gateway
  video-gateway:
    image: ghcr.io/streamingriver/video-gateway:main
    restart: unless-stopped
    depends_on:
      - video-transcoding
    


