version: '3.5'
services:
  web:
    image: caddy:latest
    restart: unless-stopped
    env_file: .env
    volumes: 
       - ./caddy:/data
       - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - video-gateway
  sr-admin-gui:
    image: ghcr.io/streamingriver/opensource-iptv:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - sr-nats-proxy
    volumes:
      - ./.env:/var/www/html/.env:z
  nats:
    image: nats:latest
    restart: unless-stopped
  sr-nats-proxy:
    image: ghcr.io/streamingriver/go-http-nats-proxy:latest
    restart: unless-stopped
    depends_on:
      - nats
  video-transcoder:
    image: ghcr.io/streamingriver/video-transcoder:latest
    restart: unless-stopped
    depends_on:
      - nats
      - video-gateway
    env_file: .env
  video-gateway:
    image: ghcr.io/streamingriver/video-gateway:main
    restart: unless-stopped
