name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create .env file
        run: cp env.example .env
      - name: Build the stack
        run: docker-compose up -d
      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env
      - name: Test Caddy
        run: |
              docker run --rm --network docker-streamingriver_default curlimages/curl -v --silent http://web/ 2>&1
      - name: Test sr-admin-gui
        run: |
             docker run --rm --network docker-streamingriver_default curlimages/curl -v --silent http://sr-admin-gui/ 2>&1
      - name: Test video-gateway
        run: |
             docker run --rm --network docker-streamingriver_default curlimages/curl -v --silent http://video-gateway/ 2>&1
